### ISSUE TITLE
How to get Intent from PianoId.signIn()

### ISSUE THREAD

**Issue by shukerullah** [tinypass/piano-sdk-for-android#25]
After upgrading SDK to the latest version (2.1.1). Im unable to get Intent from `PianoId.signIn()`
```
Intent intent = PianoId.signIn().widget(PianoId.WIDGET_LOGIN).getIntent(reactContext);
```

Is there a way to get `Intent` instead `SignInContext`?

**Comment by DeKaN** [comment]
We use [Activity Result API](https://developer.android.com/training/basics/intents/result) since version [2.1.0](https://github.com/tinypass/piano-sdk-for-android/blob/master/CHANGELOG.md#v210).
 Also, we've changed the result type, don't forget to update processing it in your code.

 See sample: [1](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample-ktx/src/main/java/io/piano/sample/MainActivity.kt#L43-L52) and [2](https://github.com/tinypass/piano-sdk-for-android/blob/master/sample-ktx/src/main/java/io/piano/sample/MainActivity.kt#L65)

**Comment by shukerullah** [comment]
I am using Piano SDK in react native. I can not use [Activity Result API](https://developer.android.com/training/basics/intents/result), because `registerForActivityResult` is not found in `ReactActivity`. Is there a way to get `Intent` so I can use `startActivityForResult` instead?

**Comment by DeKaN** [comment]
Activity Result API is part of `androidx.activity.ComponentActivity`
`ReactActivity` extends [androidx.appcompat.app.AppCompatActivity](https://developer.android.com/reference/androidx/appcompat/app/AppCompatActivity), which extends `androidx.activity.ComponentActivity`. So, it should be available

**Comment by shukerullah** [comment]
Yes, It's available.
