### ISSUE TITLE
Register API

### ISSUE THREAD

**Issue by super0610** [tinypass/piano-sdk-for-android#27]
Hi.
I am developing one app and going to implement User register/login by Piano.
I looked API documentation, and looked API sdk (2.0.1), but couldn't find Register api from latest API SDK.

Our app has register screen (email, password only), and want to implement register with Register API.
Should I call api directly in app (https://api.piano.io/id/api/v1//publisher/register, by retrofit), or is there any other way?

Please help me asap.

**Comment by DeKaN** [comment]
Hi, 
If you want to use ID for auth/register, you should call SDK's `PianoId.signIn()` as described [here](https://github.com/tinypass/piano-sdk-for-android/blob/master/id/README.md)
You can use `PianoId.signIn().widget(PianoId.WIDGET_REGISTER)`, if you want user to see `registration` instead of `login` first.

**Comment by super0610** [comment]
Hi, Thanks for your reply.
What I want is to have our custom register/login screen.
So I decided to go with api integration. But facing issues about register api is failed.

At the moment, I use sandbox base url as "https://sandbox.piano.io/id/api/v1", but the server response is like below.
"error_code_list": [
        {
            "message": "HTTP 415 Unsupported Media Type"
        }
    ]

What am I wrong?

**Comment by DeKaN** [comment]
If you want to create your own registration screen and use API directly instead of using preconfigured via Piano Dashboard, you should start from [here](https://docs.piano.io/api?endpoint=post~2F~2Fpublisher~2Fregister). If you have any questions about API, I recommend you write it to support@piano.io
